env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  camelcase: error
  complexity: error
  eol-last: error
  eqeqeq: error
  no-unused-vars: error
  prefer-const: error
  no-var: error
